name: resiboscan
description: A receipt scanner and organizer app.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/