name: resiboscan
description: A receipt scanner and organizer app.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/scanner.png
    - assets/images/folder.png
    - assets/images/expense.png
